const BACKEND_BASE_URL = "http://localhost:3001";
const WEBSOCKET_URL = "ws://localhost:8080";
const TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjMzRiZTU5Yi03NTI3LTRjODQtOGE4ZS0xNWZlOGUzYjMxMzEiLCJpYXQiOjE3NDk5NjM1OTV9.nQ6JJTFVVQgnkOjIS_z-LBB8wwpE79U8E9icSzEIAEY";
export { BACKEND_BASE_URL, WEBSOCKET_URL, TOKEN };
