const BACKEND_BASE_URL = "http://localhost:3001";
const WEBSOCKET_URL = "ws://localhost:8080";
const TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjMzRiZTU5Yi03NTI3LTRjODQtOGE4ZS0xNWZlOGUzYjMxMzEiLCJpYXQiOjE3NDk4Mjk5NTd9.-M12R9SFeofnuvgkeKwe3AehjKfmNoH2VReRMZQ-sK4";
export { BACKEND_BASE_URL, WEBSOCKET_URL, TOKEN };
